# Generated by Django 5.2.3 on 2025-06-20 11:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_order_question_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='text_html',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Formatted HTML Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_raw',
            field=models.TextField(blank=True, null=True, verbose_name='Plain Question Text'),
        ),
    ]
