# Generated by Django 5.2.3 on 2025-06-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_question_text_question_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
