# Generated by Django 5.2.3 on 2025-06-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='status',
            field=models.CharField(choices=[('not_attempted', 'Not Attempted'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_attempted', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
