# Generated by Django 5.2.3 on 2025-06-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_videoprogress_answers_videoprogress_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprogress',
            name='status',
            field=models.CharField(choices=[('not_attempted', 'Not Attempted'), ('passed', 'Passed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('timeout', 'Timeout')], default='not_attempted', max_length=20),
        ),
    ]
