# Generated by Django 5.2.3 on 2025-06-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_deleted',
        ),
    ]
