# Generated by Django 5.2.3 on 2025-06-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_question_is_deleted_remove_video_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
