# Generated by Django 5.2.3 on 2025-06-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_is_deleted_to_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_deleted',
        ),
    ]
