# Generated by Django 5.2.3 on 2025-06-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_video_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
    ]
